version: "3.3"
services:
  log-export-container:
    image: public.ecr.aws/strongdm/log-export-container:latest
    ports:
      - "5140:5140"
      - "24321:24321"
    environment:
      # IMPORTANT: Do not enclose values in double or single quotes

      # Required variables
      - LOG_EXPORT_CONTAINER_INPUT=syslog-json # possible values = syslog-json, syslog-csv, tcp-json, tcp-csv, file-json and file-csv
      - LOG_EXPORT_CONTAINER_OUTPUT=stdout # possible values = stdout, remote-syslog, s3, cloudwatch, splunk-hec, datadog, azure-loganalytics, sumologic, kafka, mongo, loki, elasticsearch-8, bigquery

      # Optional variables
      # For LOG_EXPORT_CONTAINER_OUTPUT=remote-syslog refer to docs/CONFIGURE_REMOTE_SYSLOG.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=s3 refer to docs/CONFIGURE_S3.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=cloudwatch refer to docs/CONFIGURE_CLOUDWATCH.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=splunk-hec refer to docs/CONFIGURE_SPLUNK_HEC.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=datadog refer to docs/CONFIGURE_DATADOG.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=azure-loganalytics refer to docs/CONFIGURE_AZURE_LOGANALYTICS.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=sumologic refer to docs/CONFIGURE_SUMOLOGIC.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=kafka refer to docs/CONFIGURE_KAFKA.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=mongo refer to docs/CONFIGURE_MONGO.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=logz refer to docs/CONFIGURE_LOGZ.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=loki refer to docs/CONFIGURE_LOKI.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=elasticsearch-8 refer to docs/CONFIGURE_ELASTICSEARCH_8.md
      # For LOG_EXPORT_CONTAINER_OUTPUT=bigquery refer to docs/CONFIGURE_BIGQUERY.md

